---
driver:
  name: docker
#enble to true if you are not s root on your workstation  
use_sudo: false

platforms:
  - name: ubuntu-14.04
    driver:
       image: rndmh3ro/docker-ubuntu1404-ansible:latest
       platform: ubuntu


provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  roles_path: roles
  ansible_verbose: false
  ansible_verbosity: 2
  require_ansible_repo: false
  require_ansible_omnibus: false
  require_chef_for_busser: false
  ansible_connection: ssh


verifier:
  name: serverspec
  use_sudo: yes
  sudo_path: true

suites:
  - name: default
    verifier:
        default_pattern: true
        bundler_path: '/usr/local/bin'
        rspec_path: '/usr/local/bin'
        env_vars:
              TARGET_HOST: 127.0.0.1
              SUDO: true
